from __future__ import annotations
from typing import Protocol, Sequence, Optional, Tuple
from datetime import date
from data_sanitizer.domain.models import PriceBar

class PricesRepo(Protocol):
    def last_price_date(self, isin: str, symbol: str) -> Optional[date]: ...
    def upsert_bars(self, isin: str, symbol: str, bars: Sequence[PriceBar]) -> int: ...
    def recompute_counts(self, isin: str, symbol: str) -> Tuple[int, int]: ...
    def update_bounds(self, isin: str, symbol: str) -> None: ...
